### ISSUE TITLE
Condition doesn't work if message has an attachments

### ISSUE THREAD

**Issue by ftw-soft** [Hexanet/swiftmailer-image-embed#4]
In file /src/ImageEmbedPlugin.php:21 there is an condition:
`if ($message->getContentType() === 'text/html') {
        $message->setBody($this->embedImages($message));
}`
But if message got an attachments, then returned content type will be **multipart/mixed** and plugin will not work

**Comment by nclsHart** [comment]
Hi @ftw-soft. Thanks for the report.

I added a specific test for the case you describe but the plugin is working as expected.

In a `multipart/mixed` message, the `text/html` part will be catch during the following foreach : https://github.com/Hexanet/swiftmailer-image-embed/blob/master/src/ImageEmbedPlugin.php#L25.
